/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class BrainForm extends javax.swing.JFrame {

 public String Dataa[][]=null;
    public String[] BrainDiseases = {"Encephalitis", "Brain Lymphoma", "Parkinson Disease", "Epilepsy", "Cerebro Vascular Attack", "Encephalopathy", "Meningitis"};

    /**
     * Creates new form EyeForm
     */
    public BrainForm() {
        initComponents();
    }
    public BrainForm(String hh[][]){
        Dataa=hh;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Headache = new javax.swing.JCheckBox();
        JointPain = new javax.swing.JCheckBox();
        Seizures = new javax.swing.JCheckBox();
        InvoluntryTwiching = new javax.swing.JCheckBox();
        PersonalityChange = new javax.swing.JCheckBox();
        Confusion = new javax.swing.JCheckBox();
        Drowsiness = new javax.swing.JCheckBox();
        LossOfConsciousness = new javax.swing.JCheckBox();
        WalkingDifficulty = new javax.swing.JCheckBox();
        MusclePain = new javax.swing.JCheckBox();
        Dizziness = new javax.swing.JCheckBox();
        ChangeINSPeech = new javax.swing.JCheckBox();
        LossOfCoordination = new javax.swing.JCheckBox();
        SLowMovement = new javax.swing.JCheckBox();
        StiffNeck = new javax.swing.JCheckBox();
        Irritability = new javax.swing.JCheckBox();
        PoorDicision = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();
        Fever = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Please Select Your Symptoms");
        jLabel2.setToolTipText("");

        Headache.setText("Headache");

        JointPain.setText("Joint pain");

        Seizures.setText("Seizures");

        InvoluntryTwiching.setText("Involuntary Twiching");

        PersonalityChange.setText("Personality Change");
        PersonalityChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonalityChangeActionPerformed(evt);
            }
        });

        Confusion.setText("Confusion");

        Drowsiness.setText("Drowsiness");

        LossOfConsciousness.setText("Loss of Consciousness");

        WalkingDifficulty.setText("Walking Difficulty");

        MusclePain.setText("Muscle Pain");

        Dizziness.setText("Dizziness");

        ChangeINSPeech.setText("Chnage in Speech or Vision");

        LossOfCoordination.setText("Loss of Coordination");

        SLowMovement.setText("Slow Movement");

        StiffNeck.setText("Stiff Neck");

        Irritability.setText("Irritability");

        PoorDicision.setText("Poor Decision Making");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/BackBUtton.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        Fever.setText("Fever");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Headache, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ChangeINSPeech, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LossOfConsciousness, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(PersonalityChange, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(PoorDicision, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Irritability, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LossOfCoordination, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JointPain, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Confusion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(InvoluntryTwiching, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WalkingDifficulty, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Fever))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(StiffNeck, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MusclePain)
                            .addComponent(Drowsiness)
                            .addComponent(Seizures, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SLowMovement, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dizziness, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Headache)
                    .addComponent(JointPain)
                    .addComponent(Seizures))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PersonalityChange)
                    .addComponent(Confusion)
                    .addComponent(Drowsiness))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ChangeINSPeech)
                    .addComponent(LossOfCoordination)
                    .addComponent(SLowMovement))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(LossOfConsciousness)
                    .addComponent(WalkingDifficulty)
                    .addComponent(Dizziness))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoorDicision)
                    .addComponent(InvoluntryTwiching)
                    .addComponent(StiffNeck))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Irritability)
                    .addComponent(MusclePain)
                    .addComponent(Fever))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new DepartmentsList(Dataa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
     
        if (isvalidated()) {

          int  n= GuessDisease();
          new BrainResults(n,BrainDiseases,Dataa ).setVisible(true);
          this.dispose();
        }
            
    }//GEN-LAST:event_NextButtonActionPerformed

    public int GuessDisease() {
        int n = 0;
        if (Headache.isSelected() && Fever.isSelected() && JointPain.isSelected()&& Seizures.isSelected()&& PersonalityChange.isSelected() &&Confusion.isSelected()&& Drowsiness.isSelected() ) {
            
                            n = 0;
                      
            
        } else if (ChangeINSPeech.isSelected() && Confusion.isSelected()&& Fever.isSelected()&& Seizures.isSelected() && LossOfCoordination.isSelected()) {
            n = 1;
        } else if (ChangeINSPeech.isSelected() && SLowMovement.isSelected() ) {
            n = 2;
        } else if (LossOfConsciousness.isSelected() ) {
            n = 3;
        }
        
        else   if (WalkingDifficulty.isSelected() && Dizziness.isSelected()) {
            n = 4;
        }
        else   if (PoorDicision.isSelected() ) {
            n = 5;
        }
        else if(StiffNeck.isSelected()&& Confusion.isSelected()&&Irritability.isSelected()&&Headache.isSelected()&&Fever.isSelected()){
            n=8;
        }
        else n=0;
    return n;
    }

    private void PersonalityChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalityChangeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PersonalityChangeActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox ChangeINSPeech;
    private javax.swing.JCheckBox Confusion;
    private javax.swing.JCheckBox Dizziness;
    private javax.swing.JCheckBox Drowsiness;
    private javax.swing.JCheckBox Fever;
    private javax.swing.JCheckBox Headache;
    private javax.swing.JCheckBox InvoluntryTwiching;
    private javax.swing.JCheckBox Irritability;
    private javax.swing.JCheckBox JointPain;
    private javax.swing.JCheckBox LossOfConsciousness;
    private javax.swing.JCheckBox LossOfCoordination;
    private javax.swing.JCheckBox MusclePain;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox PersonalityChange;
    private javax.swing.JCheckBox PoorDicision;
    private javax.swing.JCheckBox SLowMovement;
    private javax.swing.JCheckBox Seizures;
    private javax.swing.JCheckBox StiffNeck;
    private javax.swing.JCheckBox WalkingDifficulty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private boolean isvalidated() {
        if (!((Headache.isSelected()) || (JointPain.isSelected()) || (Seizures.isSelected()) || (PersonalityChange.isSelected()) || (Confusion.isSelected()) || (Drowsiness.isSelected()) || (ChangeINSPeech.isSelected()) || (LossOfCoordination.isSelected()) || (SLowMovement.isSelected()) || (LossOfConsciousness.isSelected()) || (WalkingDifficulty.isSelected()) || (Dizziness.isSelected()) || (PoorDicision.isSelected()) || (InvoluntryTwiching.isSelected()) || (StiffNeck.isSelected()) || (Irritability.isSelected()) || (MusclePain.isSelected()))) {
            JOptionPane.showMessageDialog(null, "One of the symptom must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
