/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class DepartmentsList extends javax.swing.JFrame {

    public String dataaa[][];

    /**
     * Creates new form DepartmentsList
     */
    public DepartmentsList() {
        initComponents();
    }

    DepartmentsList(String[][] Dataa) {
        dataaa = Dataa;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EyeRadioButton = new javax.swing.JRadioButton();
        RespiratoryRadioButton = new javax.swing.JRadioButton();
        DigestiveRadioButton = new javax.swing.JRadioButton();
        ENTRadioButton = new javax.swing.JRadioButton();
        BrainRadioButton = new javax.swing.JRadioButton();
        CardiologyRadioButton = new javax.swing.JRadioButton();
        UrologyRadioButton = new javax.swing.JRadioButton();
        DermatologyRadioButton = new javax.swing.JRadioButton();
        NotinLIstRadioButton = new javax.swing.JRadioButton();
        NextButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(661, 557));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Please Select Your Desired Department");

        buttonGroup1.add(EyeRadioButton);
        EyeRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        EyeRadioButton.setSelected(true);
        EyeRadioButton.setText("EYE");

        buttonGroup1.add(RespiratoryRadioButton);
        RespiratoryRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        RespiratoryRadioButton.setText("RESPIRATORY");

        buttonGroup1.add(DigestiveRadioButton);
        DigestiveRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DigestiveRadioButton.setText("DIGESTIVE");

        buttonGroup1.add(ENTRadioButton);
        ENTRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ENTRadioButton.setText("ENT");

        buttonGroup1.add(BrainRadioButton);
        BrainRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BrainRadioButton.setText("BRAIN");

        buttonGroup1.add(CardiologyRadioButton);
        CardiologyRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        CardiologyRadioButton.setText("CARDIOLOGY");

        buttonGroup1.add(UrologyRadioButton);
        UrologyRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        UrologyRadioButton.setText("UROLOGY");

        buttonGroup1.add(DermatologyRadioButton);
        DermatologyRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        DermatologyRadioButton.setText("DERMATOLOGY");

        buttonGroup1.add(NotinLIstRadioButton);
        NotinLIstRadioButton.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        NotinLIstRadioButton.setText("Department not in List");
        NotinLIstRadioButton.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                NotinLIstRadioButtonStateChanged(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        ExitButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        ExitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/exitButton.png"))); // NOI18N
        ExitButton.setText("Back to Home");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("Enter Your Desired Department Here (if Not in List)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(UrologyRadioButton)
                                            .addComponent(EyeRadioButton)
                                            .addComponent(DigestiveRadioButton)
                                            .addComponent(BrainRadioButton)
                                            .addComponent(jLabel3)
                                            .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DermatologyRadioButton)
                                    .addComponent(RespiratoryRadioButton)
                                    .addComponent(ENTRadioButton)
                                    .addComponent(CardiologyRadioButton))
                                .addGap(16, 16, 16))
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(NotinLIstRadioButton)
                        .addGap(249, 249, 249))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(EyeRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(DigestiveRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ENTRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(RespiratoryRadioButton)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BrainRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(UrologyRadioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CardiologyRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(DermatologyRadioButton)))
                .addGap(14, 14, 14)
                .addComponent(NotinLIstRadioButton)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        if (isValidated()) {

            if (EyeRadioButton.isSelected()) {
                new EyeForm(dataaa).setVisible(true);
                this.dispose();
            } else if (ENTRadioButton.isSelected()) {
                new ENTForm(dataaa).setVisible(true);
                this.dispose();
            } else if (DigestiveRadioButton.isSelected()) {
                new DigestiveForm(dataaa).setVisible(true);
                this.dispose();
            } else if (RespiratoryRadioButton.isSelected()) {
                new Respiratory(dataaa).setVisible(true);
                this.dispose();
            } else if (BrainRadioButton.isSelected()) {
                new BrainForm(dataaa).setVisible(true);
                this.dispose();
            } else if (CardiologyRadioButton.isSelected()) {
                new CardiologyForm(dataaa).setVisible(true);
                this.dispose();
            } else if (UrologyRadioButton.isSelected()) {
                new UrologyForm(dataaa).setVisible(true);
                this.dispose();
            } else if (DermatologyRadioButton.isSelected()) {
                new DermatologyForm(dataaa).setVisible(true);
                this.dispose();
            } else if (NotinLIstRadioButton.isSelected()) {
                JOptionPane.showMessageDialog(null, "We are Working on " + jTextField1.getText().trim() + " Department.\nSonn added here", "Information", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_NextButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed

          if (JOptionPane.showConfirmDialog(null, "Are You Sure?", "Warning", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            new Main().setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void NotinLIstRadioButtonStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_NotinLIstRadioButtonStateChanged
        if (NotinLIstRadioButton.isSelected()) {
            jTextField1.setVisible(true);
            jLabel3.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_NotinLIstRadioButtonStateChanged

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTextField1.setVisible(false);
        jLabel3.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton BrainRadioButton;
    private javax.swing.JRadioButton CardiologyRadioButton;
    private javax.swing.JRadioButton DermatologyRadioButton;
    private javax.swing.JRadioButton DigestiveRadioButton;
    private javax.swing.JRadioButton ENTRadioButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JRadioButton EyeRadioButton;
    private javax.swing.JButton NextButton;
    private javax.swing.JRadioButton NotinLIstRadioButton;
    private javax.swing.JRadioButton RespiratoryRadioButton;
    private javax.swing.JRadioButton UrologyRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private boolean isValidated() {
        if (NotinLIstRadioButton.isSelected()) {
            if (jTextField1.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(null, "Please Enter Your Desired Department", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().trim().contains(",")) {
                JOptionPane.showMessageDialog(null, "Please Enter Valid Department. Commas Not Allowed Here", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("eye")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("ent")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("digestive")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("respiratory")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("brain")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("cardiology") || jTextField1.getText().equalsIgnoreCase("heart")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("Urology")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("dermatology")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("gynecology")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("Skeletal")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }
            if (jTextField1.getText().equalsIgnoreCase("Muscles")) {
                JOptionPane.showMessageDialog(null, "Department Already in List ", "Error", JOptionPane.ERROR_MESSAGE);
                jTextField1.requestFocus();
                jTextField1.setText("");
                return false;
            }

        }
        return true;
    }
}
