/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class DermatologyForm extends javax.swing.JFrame {
public String Dataa[][]=null;
 
    public String[] BrainDiseases = {"Dermatitis", "Eczema", "Allergic Skin Disease", "Acne", "Moles"};

    /**
     * Creates new form EyeForm
     */
    public DermatologyForm() {
        initComponents();
    }
    public DermatologyForm(String[][]data){
        Dataa=data;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        RedRash = new javax.swing.JCheckBox();
        Itching = new javax.swing.JCheckBox();
        ScalySkin = new javax.swing.JCheckBox();
        Blackheads = new javax.swing.JCheckBox();
        Bumps = new javax.swing.JCheckBox();
        Swelling = new javax.swing.JCheckBox();
        Burning = new javax.swing.JCheckBox();
        OozingBlisters = new javax.swing.JCheckBox();
        SkinRedness = new javax.swing.JCheckBox();
        DaekenedSkin = new javax.swing.JCheckBox();
        Redness = new javax.swing.JCheckBox();
        Cracks = new javax.swing.JCheckBox();
        Hives = new javax.swing.JCheckBox();
        SoreNotHeal = new javax.swing.JCheckBox();
        SpreadPigments = new javax.swing.JCheckBox();
        Whiteheads = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Please Select Your Symptoms");
        jLabel2.setToolTipText("");

        RedRash.setText("Red Rashes");

        Itching.setText("Itching");

        ScalySkin.setText("Scaly,Dry Skin");

        Blackheads.setText("Blackheads");

        Bumps.setText("Bumps");
        Bumps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BumpsActionPerformed(evt);
            }
        });

        Swelling.setText("Swelling");

        Burning.setText("Burning");

        OozingBlisters.setText("OozingBlisters");

        SkinRedness.setText("Skin Redness");

        DaekenedSkin.setText("Darkened Skin");

        Redness.setText("Redness");

        Cracks.setText("Cracks Behind Ears");

        Hives.setText("Hives");

        SoreNotHeal.setText("Sore doesn't heal");

        SpreadPigments.setText("Spread Pigments in Skin");

        Whiteheads.setText("Whiteheads");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/BackBUtton.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(RedRash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Redness, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(OozingBlisters, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(Bumps, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(Whiteheads, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(SpreadPigments, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cracks, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Itching, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Swelling, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Blackheads, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SkinRedness, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SoreNotHeal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Burning)
                            .addComponent(ScalySkin, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hives, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DaekenedSkin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(RedRash)
                    .addComponent(Itching)
                    .addComponent(ScalySkin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bumps)
                    .addComponent(Swelling)
                    .addComponent(Burning))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Redness)
                    .addComponent(Cracks)
                    .addComponent(Hives))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(OozingBlisters)
                    .addComponent(SkinRedness)
                    .addComponent(DaekenedSkin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Whiteheads)
                    .addComponent(Blackheads)
                    .addComponent(SoreNotHeal))
                .addGap(18, 18, 18)
                .addComponent(SpreadPigments)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new DepartmentsList(Dataa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
     
        if (isvalidated()) {

          int  n= GuessDisease();
          new DermatologyResults(n,BrainDiseases,Dataa ).setVisible(true);
          this.dispose();
        }
            
    }//GEN-LAST:event_NextButtonActionPerformed

    public int GuessDisease() {
        int n = 0;
        if (RedRash.isSelected() && Itching.isSelected() && ScalySkin.isSelected()&& Bumps.isSelected() &&Swelling.isSelected()&& Burning.isSelected() ) {
            
                            n = 0;
                      
            
        } else if (Redness.isSelected() && Cracks.isSelected()&& ScalySkin.isSelected() && Itching.isSelected()) {
            n = 1;
        } else if (OozingBlisters.isSelected() && Hives.isSelected() && Redness.isSelected()&&DaekenedSkin.isSelected()) {
            n = 2;
        } else if (Bumps.isSelected() &&Blackheads.isSelected()&&Whiteheads.isSelected() ) {
            n = 3;
        }
        
        else   if (SoreNotHeal.isSelected() && SpreadPigments.isSelected()) {
            n = 4;
        }
        
        else n=0;
    return n;
    }

    private void BumpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BumpsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BumpsActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox Blackheads;
    private javax.swing.JCheckBox Bumps;
    private javax.swing.JCheckBox Burning;
    private javax.swing.JCheckBox Cracks;
    private javax.swing.JCheckBox DaekenedSkin;
    private javax.swing.JCheckBox Hives;
    private javax.swing.JCheckBox Itching;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox OozingBlisters;
    private javax.swing.JCheckBox RedRash;
    private javax.swing.JCheckBox Redness;
    private javax.swing.JCheckBox ScalySkin;
    private javax.swing.JCheckBox SkinRedness;
    private javax.swing.JCheckBox SoreNotHeal;
    private javax.swing.JCheckBox SpreadPigments;
    private javax.swing.JCheckBox Swelling;
    private javax.swing.JCheckBox Whiteheads;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private boolean isvalidated() {
        if (!((RedRash.isSelected()) || (Itching.isSelected()) || (ScalySkin.isSelected()) || (Bumps.isSelected()) || (Swelling.isSelected()) || (Burning.isSelected()) || (Redness.isSelected()) || (Cracks.isSelected()) || (Hives.isSelected()) || (OozingBlisters.isSelected()) || (SkinRedness.isSelected()) || (DaekenedSkin.isSelected()) || (Whiteheads.isSelected()) || (Blackheads.isSelected()) || (SoreNotHeal.isSelected()) || (SpreadPigments.isSelected()) )) {
            JOptionPane.showMessageDialog(null, "One of the symptom must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
