/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class EyeForm extends javax.swing.JFrame {

 public String[][] ID;
    public String[] EyeDiseases = {"Conjunctivitis", "Blepharitis", "Sty", "Chlazion", "Scleritis", "Keratoconjunctivitis", "Cataract", "Glaucoma", "Diabetic Retinopathy", "Optic Neuritis", "Maculopathy"};

    /**
     * Creates new form EyeForm
     */
    public EyeForm() {
        initComponents();
    }
     public EyeForm(String[][] id) {
         ID=id;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Iritation = new javax.swing.JCheckBox();
        Etching = new javax.swing.JCheckBox();
        Watering = new javax.swing.JCheckBox();
        Burning = new javax.swing.JCheckBox();
        Redness = new javax.swing.JCheckBox();
        ScaringEyeLids = new javax.swing.JCheckBox();
        SwalingsMargins = new javax.swing.JCheckBox();
        swellingEyeLids = new javax.swing.JCheckBox();
        photophibia = new javax.swing.JCheckBox();
        Dimness = new javax.swing.JCheckBox();
        bluring = new javax.swing.JCheckBox();
        Nausea = new javax.swing.JCheckBox();
        Hemorrhage = new javax.swing.JCheckBox();
        COngestion = new javax.swing.JCheckBox();
        Odema = new javax.swing.JCheckBox();
        SeverePain = new javax.swing.JCheckBox();
        totalvisionloss = new javax.swing.JCheckBox();
        GradualLossSugar = new javax.swing.JCheckBox();
        GrdaualLoss = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Please Select Your Symptoms");
        jLabel2.setToolTipText("");

        Iritation.setText("Irritation");

        Etching.setText("Etching");

        Watering.setText("Watering");

        Burning.setText("Burning Sensation");

        Redness.setText("Redness");
        Redness.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RednessActionPerformed(evt);
            }
        });

        ScaringEyeLids.setText("Scaring of eye lids");

        SwalingsMargins.setText("Swelling on Eye lids Margins");

        swellingEyeLids.setText("Swelling on Eye Lids");

        photophibia.setText("Photophobia");

        Dimness.setText("Dimness of Vision");

        bluring.setText("Bluring of Vision");

        Nausea.setText("Nausea");

        Hemorrhage.setText("Subconjunctival Hemorrhage");

        COngestion.setText("Conjunctival Congestion");

        Odema.setText("Conjunctival Oedma ");

        SeverePain.setText("Severe Pain");

        totalvisionloss.setText("Gradual Loss of Vision resulting Total loss of vision");

        GradualLossSugar.setText("Gradual Loss of Vision due to Sugar Level");

        GrdaualLoss.setText("Gradual Loss of Vision without Sugar Level");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/BackBUtton.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Iritation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Hemorrhage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(photophibia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Redness, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(GradualLossSugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(COngestion, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Etching, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ScaringEyeLids, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Burning, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Dimness, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(SeverePain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(bluring)
                                            .addComponent(SwalingsMargins)
                                            .addComponent(Watering, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Odema, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Nausea, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(swellingEyeLids, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(GrdaualLoss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(totalvisionloss, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(409, 409, 409)
                                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Iritation)
                    .addComponent(Etching)
                    .addComponent(Watering))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Redness)
                    .addComponent(ScaringEyeLids)
                    .addComponent(SwalingsMargins))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Hemorrhage)
                    .addComponent(COngestion)
                    .addComponent(Odema))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(photophibia)
                    .addComponent(Dimness)
                    .addComponent(Nausea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GradualLossSugar)
                    .addComponent(Burning)
                    .addComponent(SeverePain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalvisionloss)
                    .addComponent(bluring))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(GrdaualLoss)
                    .addComponent(swellingEyeLids))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new DepartmentsList(ID).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
     
        if (isvalidated()) {

          int  n= GuessDisease();
          new EyeResults(n,EyeDiseases,ID ).setVisible(true);
          this.dispose();
        }
            
    }//GEN-LAST:event_NextButtonActionPerformed

    public int GuessDisease() {
        int n = 0;
        if (Iritation.isSelected()) {
            if (Etching.isSelected()) {
                if (Watering.isSelected()) {
                    if (Burning.isSelected()) {
                        if (Redness.isSelected()) {
                            n = 0;
                        }
                    }
                    if (SeverePain.isSelected()) {
                        if (photophibia.isSelected()) {
                            n = 5;
                        }
                    }
                }
                if (ScaringEyeLids.isSelected()) {
                    n = 1;
                }
            }
            
        } else if (SwalingsMargins.isSelected()) {
            n = 2;
        } else if (swellingEyeLids.isSelected()) {
            n = 3;
        } else if (Hemorrhage.isSelected() && COngestion.isSelected() && Odema.isSelected()) {
            n = 4;
        }
        
        else   if (Dimness.isSelected()) {
            n = 6;
        }
        else   if (bluring.isSelected() && Nausea.isSelected() && Redness.isSelected() && SeverePain.isSelected()) {
            n = 7;
        }
        else if(GradualLossSugar.isSelected()){
            n=8;
        }
        else if(GrdaualLoss.isSelected()){
            n=9;
        }
        else if(totalvisionloss.isSelected()){
            n=10;
        }
    return n;
    }

    private void RednessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RednessActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RednessActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox Burning;
    private javax.swing.JCheckBox COngestion;
    private javax.swing.JCheckBox Dimness;
    private javax.swing.JCheckBox Etching;
    private javax.swing.JCheckBox GradualLossSugar;
    private javax.swing.JCheckBox GrdaualLoss;
    private javax.swing.JCheckBox Hemorrhage;
    private javax.swing.JCheckBox Iritation;
    private javax.swing.JCheckBox Nausea;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox Odema;
    private javax.swing.JCheckBox Redness;
    private javax.swing.JCheckBox ScaringEyeLids;
    private javax.swing.JCheckBox SeverePain;
    private javax.swing.JCheckBox SwalingsMargins;
    private javax.swing.JCheckBox Watering;
    private javax.swing.JCheckBox bluring;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JCheckBox photophibia;
    private javax.swing.JCheckBox swellingEyeLids;
    private javax.swing.JCheckBox totalvisionloss;
    // End of variables declaration//GEN-END:variables

    private boolean isvalidated() {
        if (!((Iritation.isSelected()) || (Etching.isSelected()) || (Watering.isSelected()) || (Redness.isSelected()) || (ScaringEyeLids.isSelected()) || (SwalingsMargins.isSelected()) || (Hemorrhage.isSelected()) || (COngestion.isSelected()) || (Odema.isSelected()) || (photophibia.isSelected()) || (Dimness.isSelected()) || (Nausea.isSelected()) || (GradualLossSugar.isSelected()) || (Burning.isSelected()) || (SeverePain.isSelected()) || (totalvisionloss.isSelected()) || (bluring.isSelected()) || (GrdaualLoss.isSelected()) || (swellingEyeLids.isSelected()))) {
            JOptionPane.showMessageDialog(null, "One of the symptom must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
