/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class Respiratory extends javax.swing.JFrame {
public String[][]Dataa=null;
    public String[] RespiratoryDiseases = {"URTI", "Bronchitis", "Asthmatic bronchitis", "TB", "Asthma", "Pluritis", "Lungs Cancer", "Cardiac Asthma","COPD"};

    /**
     * Creates new form EyeForm
     */
    public Respiratory() {
        initComponents();
    }
    public Respiratory(String[][]Data){
    Dataa=Data;
    initComponents();
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BreathingDifficulty = new javax.swing.JCheckBox();
        ChestPain = new javax.swing.JCheckBox();
        WeightLoss = new javax.swing.JCheckBox();
        Sweating = new javax.swing.JCheckBox();
        GeneralWeakness = new javax.swing.JCheckBox();
        BloodWithSputum = new javax.swing.JCheckBox();
        MildCoughing = new javax.swing.JCheckBox();
        Flue = new javax.swing.JCheckBox();
        Fever = new javax.swing.JCheckBox();
        LungsSputum = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Please Select Your Symptoms");
        jLabel2.setToolTipText("");

        BreathingDifficulty.setText("Breathing Difficulty");

        ChestPain.setText("Chest Pain");

        WeightLoss.setText("Weight Loss");

        Sweating.setText("Sweating");
        Sweating.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SweatingActionPerformed(evt);
            }
        });

        GeneralWeakness.setText("General Weakness");

        BloodWithSputum.setText("Inflamation of Internal Ear");

        MildCoughing.setText("Mild Coughing");

        Flue.setText("Flue");

        Fever.setText("Fever");

        LungsSputum.setText("Lungs Sputum");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/BackBUtton.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BreathingDifficulty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Flue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(MildCoughing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Sweating, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 44, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Fever, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ChestPain, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(GeneralWeakness, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BloodWithSputum)
                                            .addComponent(WeightLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(LungsSputum, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(BreathingDifficulty)
                    .addComponent(ChestPain)
                    .addComponent(WeightLoss))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sweating)
                    .addComponent(GeneralWeakness)
                    .addComponent(BloodWithSputum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Flue)
                    .addComponent(Fever)
                    .addComponent(LungsSputum))
                .addGap(18, 18, 18)
                .addComponent(MildCoughing)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new DepartmentsList(Dataa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed

        if (isvalidated()) {

            int n = GuessDisease();
            new RespiratoryResults(n, RespiratoryDiseases,Dataa).setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_NextButtonActionPerformed

    public int GuessDisease() {
        int n = 0;
        if (Fever.isSelected() && Flue.isSelected() && MildCoughing.isSelected()) {
            n=0;
            if(BreathingDifficulty.isSelected()){
                n=1;
            }
        } else if (Fever.isSelected() && BreathingDifficulty.isSelected() && MildCoughing.isSelected() && ChestPain.isSelected()) {
           n=2;
        } else if (GeneralWeakness.isSelected() && Sweating.isSelected() && WeightLoss.isSelected() && BloodWithSputum.isSelected()) {
            n = 3;
        } else if (BreathingDifficulty.isSelected()) {
            n = 4;
        } else if (ChestPain.isSelected() && Fever.isSelected() && MildCoughing.isSelected() && BreathingDifficulty.isSelected()) {
            n = 5;
        } else if (BloodWithSputum.isSelected()&&Fever.isSelected() && MildCoughing.isSelected() && ChestPain.isSelected()&& BreathingDifficulty.isSelected()) {
            n = 6;}
            else if (BreathingDifficulty.isSelected() && ChestPain.isSelected()&&MildCoughing.isSelected()) 
                { n = 7;
            }
         else if (LungsSputum.isSelected()&& MildCoughing.isSelected()&& BreathingDifficulty.isSelected()){
            n = 8;
        }
         else n=0;

        return n;
    }

    private void SweatingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SweatingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SweatingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respiratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respiratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respiratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respiratory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respiratory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox BloodWithSputum;
    private javax.swing.JCheckBox BreathingDifficulty;
    private javax.swing.JCheckBox ChestPain;
    private javax.swing.JCheckBox Fever;
    private javax.swing.JCheckBox Flue;
    private javax.swing.JCheckBox GeneralWeakness;
    private javax.swing.JCheckBox LungsSputum;
    private javax.swing.JCheckBox MildCoughing;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox Sweating;
    private javax.swing.JCheckBox WeightLoss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private boolean isvalidated() {
        if (!((BreathingDifficulty.isSelected()) || (ChestPain.isSelected()) || (WeightLoss.isSelected()) || (Sweating.isSelected()) || (GeneralWeakness.isSelected()) || (BloodWithSputum.isSelected()) || (Flue.isSelected()) || (Fever.isSelected()) || (LungsSputum.isSelected()) || (MildCoughing.isSelected()))) {
            JOptionPane.showMessageDialog(null, "One of the symptom must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
