/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package virtualHospital;

import javax.swing.JOptionPane;

/**
 *
 * @author sshth
 */
public class UrologyForm extends javax.swing.JFrame {

 public String Dataa[][]=null;
    public String[] UrologyDiseases = {"UTI", "Kidney Stone", "Nephritis", "Renal Cell carcinoma"};

    /**
     * Creates new form EyeForm
     */
    public UrologyForm() {
        initComponents();
    }
    public UrologyForm(String[][]id){
        Dataa=id;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Burning = new javax.swing.JCheckBox();
        CloudyUrine = new javax.swing.JCheckBox();
        FeelingShaky = new javax.swing.JCheckBox();
        WeightLoss = new javax.swing.JCheckBox();
        FeverChills = new javax.swing.JCheckBox();
        PainInRIbs = new javax.swing.JCheckBox();
        AbdomenPain = new javax.swing.JCheckBox();
        Vomiting = new javax.swing.JCheckBox();
        PelvisPain = new javax.swing.JCheckBox();
        NightSweat = new javax.swing.JCheckBox();
        FrequentUrination = new javax.swing.JCheckBox();
        PainInUrination = new javax.swing.JCheckBox();
        PinkRedBrownUrine = new javax.swing.JCheckBox();
        Nausea = new javax.swing.JCheckBox();
        Fatigue = new javax.swing.JCheckBox();
        SwellingOfAnkles = new javax.swing.JCheckBox();
        BloodInUrine = new javax.swing.JCheckBox();
        BackButton = new javax.swing.JButton();
        NextButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/maintitle.png"))); // NOI18N
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Please Select Your Symptoms");
        jLabel2.setToolTipText("");

        Burning.setText("Burning while Urinating");

        CloudyUrine.setText("Cloudy Smelly Urine");

        FeelingShaky.setText("Feeling Shaky");

        WeightLoss.setText("Weight Loss");

        FeverChills.setText("Fever/Chills");
        FeverChills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FeverChillsActionPerformed(evt);
            }
        });

        PainInRIbs.setText("Pain below Ribs in side");

        AbdomenPain.setText("Pain in Lower Abdomen");

        Vomiting.setText("Vomiting");

        PelvisPain.setText("Pain in Pelvis");

        NightSweat.setText("Night Sweat");

        FrequentUrination.setText("Frquent Urination");

        PainInUrination.setText("Pain in Urination");

        PinkRedBrownUrine.setText("Pink,Red or Brown Urine");

        Nausea.setText("Nausea");

        Fatigue.setText("Fatigue");

        SwellingOfAnkles.setText("Swelling of Ankles");

        BloodInUrine.setText("Blood In Urine");

        BackButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        BackButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/BackBUtton.png"))); // NOI18N
        BackButton.setText("Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        NextButton.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        NextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/virtualHospital/Images/nextButton.png"))); // NOI18N
        NextButton.setText("Next");
        NextButton.setName(""); // NOI18N
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(409, 409, 409)
                        .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Burning, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PainInUrination, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Vomiting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(FeverChills, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(BloodInUrine, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(SwellingOfAnkles, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PinkRedBrownUrine, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CloudyUrine, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(WeightLoss, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PelvisPain, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PainInRIbs, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Fatigue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(NightSweat)
                            .addComponent(AbdomenPain)
                            .addComponent(FeelingShaky, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nausea, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FrequentUrination, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Burning)
                    .addComponent(CloudyUrine)
                    .addComponent(FeelingShaky))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FeverChills)
                    .addComponent(PainInRIbs)
                    .addComponent(AbdomenPain))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(PainInUrination)
                    .addComponent(PinkRedBrownUrine)
                    .addComponent(Nausea))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Vomiting)
                    .addComponent(PelvisPain)
                    .addComponent(FrequentUrination))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BloodInUrine)
                    .addComponent(WeightLoss)
                    .addComponent(Fatigue))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SwellingOfAnkles)
                    .addComponent(NightSweat))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        new DepartmentsList(Dataa).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
     
        if (isvalidated()) {

          int  n= GuessDisease();
          new UrologyResults(n,UrologyDiseases ,Dataa).setVisible(true);
          this.dispose();
        }
            
    }//GEN-LAST:event_NextButtonActionPerformed

    public int GuessDisease() {
        int n = 0;
        if (Burning.isSelected() && FeverChills.isSelected() && CloudyUrine.isSelected()&& FeelingShaky.isSelected() ) {
            
                            n = 0;
                      
            
        } else if (AbdomenPain.isSelected() && PainInRIbs.isSelected()&& PainInUrination.isSelected()&& CloudyUrine.isSelected() && PinkRedBrownUrine.isSelected()&&Nausea.isSelected()&&Vomiting.isSelected()) {
            n = 1;
        } else if (PelvisPain.isSelected() && PainInUrination.isSelected() &&FrequentUrination.isSelected() &&Vomiting.isSelected()&&CloudyUrine.isSelected()) {
            n = 2;
        } else if (BloodInUrine.isSelected()&&PainInRIbs.isSelected()&&WeightLoss.isSelected()&&Fatigue.isSelected()&&FeverChills.isSelected()&&SwellingOfAnkles.isSelected()&&NightSweat.isSelected() ) {
            n = 3;
        }
        
       
        else n=0;
    return n;
    }

    private void FeverChillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FeverChillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FeverChillsActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AbdomenPain;
    private javax.swing.JButton BackButton;
    private javax.swing.JCheckBox BloodInUrine;
    private javax.swing.JCheckBox Burning;
    private javax.swing.JCheckBox CloudyUrine;
    private javax.swing.JCheckBox Fatigue;
    private javax.swing.JCheckBox FeelingShaky;
    private javax.swing.JCheckBox FeverChills;
    private javax.swing.JCheckBox FrequentUrination;
    private javax.swing.JCheckBox Nausea;
    private javax.swing.JButton NextButton;
    private javax.swing.JCheckBox NightSweat;
    private javax.swing.JCheckBox PainInRIbs;
    private javax.swing.JCheckBox PainInUrination;
    private javax.swing.JCheckBox PelvisPain;
    private javax.swing.JCheckBox PinkRedBrownUrine;
    private javax.swing.JCheckBox SwellingOfAnkles;
    private javax.swing.JCheckBox Vomiting;
    private javax.swing.JCheckBox WeightLoss;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    private boolean isvalidated() {
        if (!((Burning.isSelected()) || (CloudyUrine.isSelected()) || (FeelingShaky.isSelected()) || (FeverChills.isSelected()) || (PainInRIbs.isSelected()) || (AbdomenPain.isSelected()) || (PainInUrination.isSelected()) || (PinkRedBrownUrine.isSelected()) || (Nausea.isSelected()) || (Vomiting.isSelected()) || (PelvisPain.isSelected()) || (FrequentUrination.isSelected()) || (BloodInUrine.isSelected()) || (WeightLoss.isSelected()) || (Fatigue.isSelected()) || (SwellingOfAnkles.isSelected()) || (NightSweat.isSelected()))) {
            JOptionPane.showMessageDialog(null, "One of the symptom must be selected", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

}
